//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class putni_naloziEntities : DbContext
    {
        public putni_naloziEntities()
            : base("name=putni_naloziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<izvjestaj_racuni> izvjestaj_racuni { get; set; }
        public DbSet<izvjestaji_kretanja_vozila> izvjestaji_kretanja_vozila { get; set; }
        public DbSet<nalozi> nalozi { get; set; }
        public DbSet<nalozi_mjesta> nalozi_mjesta { get; set; }
        public DbSet<putni_izvjestaji> putni_izvjestaji { get; set; }
        public DbSet<vozila> vozila { get; set; }
        public DbSet<zaposlenici> zaposlenici { get; set; }
    }
}
