//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class izvjestaji_kretanja_vozila
    {
        public int izvjestaj_kretanja_vozila_id { get; set; }
        public int putni_izvjestaj_id { get; set; }
        public int stanje_brojila { get; set; }
        public string mjesto { get; set; }
    
        public virtual putni_izvjestaji putni_izvjestaji { get; set; }
    }
}
