//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class izvjestaj_racuni
    {
        public int izvjestaj_racun_id { get; set; }
        public int putni_izvjestaj_id { get; set; }
        public int tip_racuna { get; set; }
        public System.DateTime datum_vrijeme { get; set; }
        public string racun_izdao { get; set; }
        public string broj_racuna { get; set; }
        public double iznos { get; set; }
    
        public virtual putni_izvjestaji putni_izvjestaji { get; set; }
    }
}
