//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class nalozi
    {
        public nalozi()
        {
            this.nalozi_mjesta = new HashSet<nalozi_mjesta>();
            this.putni_izvjestaji = new HashSet<putni_izvjestaji>();
        }
    
        public int nalog_id { get; set; }
        public int zaposlenik_id { get; set; }
        public int vozilo_id { get; set; }
        public System.DateTime vrijeme_polaska { get; set; }
        public System.DateTime vrijeme_dolaska { get; set; }
        public string svrha { get; set; }
        public double trosak_puta { get; set; }
        public int nalog_kreirao { get; set; }
        public System.DateTime datum_kreiranja { get; set; }
        public System.DateTime dat_zad_izmjene { get; set; }
        public int zap_zad_izmjene { get; set; }
    
        public virtual ICollection<nalozi_mjesta> nalozi_mjesta { get; set; }
        public virtual vozila vozila { get; set; }
        public virtual zaposlenici zaposlenici { get; set; }
        public virtual zaposlenici zaposlenici1 { get; set; }
        public virtual zaposlenici zaposlenici2 { get; set; }
        public virtual ICollection<putni_izvjestaji> putni_izvjestaji { get; set; }
    }
}
