//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class nalozi_mjesta
    {
        public int nalog_mjesta_id { get; set; }
        public Nullable<int> nalog_id { get; set; }
        public string naziv_mjesta { get; set; }
    
        public virtual nalozi nalozi { get; set; }
    }
}
