//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class putni_izvjestaji
    {
        public putni_izvjestaji()
        {
            this.izvjestaj_racuni = new HashSet<izvjestaj_racuni>();
            this.izvjestaji_kretanja_vozila = new HashSet<izvjestaji_kretanja_vozila>();
        }
    
        public int putni_izvjestaj_id { get; set; }
        public int nalog_id { get; set; }
        public System.DateTime vrijeme_polaska { get; set; }
        public System.DateTime vrijeme_dolaska { get; set; }
        public double duljina_puta { get; set; }
        public int izvjestaj_kreirao { get; set; }
        public System.DateTime datum_kreiranja { get; set; }
        public System.DateTime dat_zad_izmjene { get; set; }
        public int zap_zad_izmjene { get; set; }
    
        public virtual ICollection<izvjestaj_racuni> izvjestaj_racuni { get; set; }
        public virtual ICollection<izvjestaji_kretanja_vozila> izvjestaji_kretanja_vozila { get; set; }
        public virtual nalozi nalozi { get; set; }
        public virtual zaposlenici zaposlenici { get; set; }
    }
}
