//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vozila
    {
        public vozila()
        {
            this.nalozi = new HashSet<nalozi>();
        }
    
        public int vozilo_id { get; set; }
        public string marka { get; set; }
        public string broj_sasije { get; set; }
        public string kategorija { get; set; }
        public double nosivost { get; set; }
        public int broj_sjedala { get; set; }
        public string reg_oznaka { get; set; }
        public Nullable<System.DateTime> datum_reg { get; set; }
        public System.DateTime dat_zad_izmjene { get; set; }
        public int zap_zad_izmjene { get; set; }
    
        public virtual ICollection<nalozi> nalozi { get; set; }
        public virtual zaposlenici zaposlenici { get; set; }
    }
}
