//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace putni_nalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenici
    {
        public zaposlenici()
        {
            this.nalozi = new HashSet<nalozi>();
            this.nalozi1 = new HashSet<nalozi>();
            this.nalozi2 = new HashSet<nalozi>();
            this.putni_izvjestaji = new HashSet<putni_izvjestaji>();
            this.vozila = new HashSet<vozila>();
            this.zaposlenici1 = new HashSet<zaposlenici>();
        }
    
        public int zaposlenik_id { get; set; }
        public string prezime { get; set; }
        public string ime { get; set; }
        public int kat_a { get; set; }
        public int kat_b { get; set; }
        public int kat_c { get; set; }
        public int kat_d { get; set; }
        public int kat_e { get; set; }
        public System.DateTime dat_zad_izmjene { get; set; }
        public Nullable<int> zap_zad_izmjene { get; set; }
    
        public virtual ICollection<nalozi> nalozi { get; set; }
        public virtual ICollection<nalozi> nalozi1 { get; set; }
        public virtual ICollection<nalozi> nalozi2 { get; set; }
        public virtual ICollection<putni_izvjestaji> putni_izvjestaji { get; set; }
        public virtual ICollection<vozila> vozila { get; set; }
        public virtual ICollection<zaposlenici> zaposlenici1 { get; set; }
        public virtual zaposlenici zaposlenici2 { get; set; }
    }
}
